// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://judunmwtvbulxqlrbluf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1ZHVubXd0dmJ1bHhxbHJibHVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MjYyNTUsImV4cCI6MjA2MzIwMjI1NX0.gZ-KZdlyXChnzBjHczNRqSHRq3Oi_ZgyC8hQxPl7N7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);